/*
===========================================================
BUSINESS ANALYSIS
Project: CareBridge Health Network Analytics
Description:
These queries answer key business questions and were used
to build the Power BI dashboards and generate insights.
===========================================================
*/

-----------------------------------------------------------
-- Executive KPIs
-----------------------------------------------------------

-- Calculate the total revenue generated by the hospital network.
SELECT SUM(amount) AS total_revenue
FROM billing_cleaned;

-- Calculate the total value of pending payments.
SELECT SUM(amount) AS pending_payments
FROM billing_cleaned
WHERE payment_status = 'Pending';

-----------------------------------------------------------
-- Financial Analysis
-----------------------------------------------------------

-- Analyse revenue generated by each payment method.
SELECT payment_method,
       SUM(amount) AS revenue
FROM billing_cleaned
GROUP BY payment_method;

-- Analyse revenue generated by each hospital branch.
SELECT d.hospital_branch,
       SUM(b.amount) AS revenue
FROM billing_cleaned b
JOIN patients_cleaned p
ON b.patient_id = p.patient_id
JOIN appointments_cleaned a
ON p.patient_id = a.patient_id
JOIN doctors_cleaned d
ON a.doctor_id = d.doctor_id
GROUP BY d.hospital_branch;

-----------------------------------------------------------
-- Treatment Analysis
-----------------------------------------------------------

-- Identify the treatments generating the highest revenue.
SELECT treatment_type,
       SUM(cost) AS revenue
FROM treatments_cleaned
GROUP BY treatment_type
ORDER BY revenue DESC;

-- Identify the most frequently performed treatments.
SELECT treatment_type,
       COUNT(*) AS total
FROM treatments_cleaned
GROUP BY treatment_type
ORDER BY total DESC;

-----------------------------------------------------------
-- Doctor Analysis
-----------------------------------------------------------

-- Identify the doctor who handled the highest number of appointments.
SELECT d.first_name,
       d.last_name,
       COUNT(a.appointment_id) AS visits
FROM doctors_cleaned d
JOIN appointments_cleaned a
ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id
ORDER BY visits DESC;

-----------------------------------------------------------
-- Operational Analysis
-----------------------------------------------------------

-- Analyse the distribution of appointments by status.
SELECT status,
       COUNT(*) AS total_appointments
FROM appointments_cleaned
GROUP BY status;

-----------------------------------------------------------
-- Patient Analysis
-----------------------------------------------------------

-- Analyse the gender distribution of patients.
SELECT gender,
       COUNT(*) AS total_patients
FROM patients_cleaned
GROUP BY gender;